import 'package:flutter/material.dart';

final langNotifier = ValueNotifier<String>('ar');

String tr(String key) => _s[key] ?? key;

const _s = {
  'tagline': 'توثيق سريع، ثقة دائمة.',
  'logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
  'cancel': 'إلغاء',
  'yes': 'نعم',
  'welcome': 'مرحباً',
  'view': 'عرض',
  // nav - user
  'nav_profile': 'حسابي',
  'nav_certificates': 'الشهادات',
  'nav_home': 'الرئيسية',
  'nav_board': 'اللوحة',
  'nav_skills': 'المهارات',
  // home cards
  'card_certs': 'عدد الشهادات',
  'card_career': 'السجل الوظيفي',
  'card_skills': 'عدد المهارات',
  // nav - company
  'nav_company_home': 'الرئيسية',
  'nav_company_profile': 'الملف',
  // nav - trainer
  'nav_trainer_home': 'الرئيسية',
  'nav_trainer_profile': 'ملف المؤسسة',

  // user_type_screen
  'ut_individual': 'أوثق أفراد',
  'ut_company': 'أوثق شركات',
  'ut_trainer': 'أوثق مؤسسات التدريب',
  'ut_admin': 'دخول المسؤول',

  // login
  'login_fill_fields': 'يرجى تعبئة جميع الحقول',
  'login_error': 'خطأ في تسجيل الدخول',
  'login_national_id': 'رقم الهوية',
  'login_commercial_reg': 'السجل التجاري',
  'login_password': 'كلمة المرور',
  'login_btn': 'دخول',
  'login_forgot': 'نسيت كلمة المرور؟',
  'login_no_account': 'ليس لديك حساب؟',
  'login_create': 'إنشاء حساب',

  // register
  'reg_pending_title': 'طلبك قيد المراجعة',
  'reg_pending_body': 'تم استلام طلب تسجيل حسابك بنجاح.\nسيتم مراجعته من قبل الإدارة وإشعارك عند الموافقة.',
  'ok': 'حسناً',
  'reg_error': 'خطأ في إنشاء الحساب',
  'reg_fill_fields': 'يرجى تعبئة جميع الحقول',
  'reg_password_weak': 'كلمة المرور لا تستوفي الشروط المطلوبة',
  'reg_password_mismatch': 'كلمة المرور غير متطابقة',
  'reg_individual': 'إنشاء حساب فرد',
  'reg_company': 'إنشاء حساب شركة',
  'reg_trainer': 'إنشاء حساب مؤسسة تدريبية',
  'reg_first_name': 'الاسم الأول',
  'reg_father_name': 'اسم الأب',
  'reg_last_name': 'اسم العائلة',
  'reg_national_id': 'رقم الهوية',
  'reg_email': 'البريد الإلكتروني',
  'reg_phone': 'رقم الجوال',
  'reg_password': 'كلمة المرور',
  'reg_confirm_password': 'تأكيد كلمة المرور',
  'reg_entity_name': 'اسم الجهة',
  'reg_entity_type': 'نوع الكيان',
  'reg_commercial_reg': 'السجل التجاري',
  'reg_tax_number': 'الرقم الضريبي',
  'reg_address': 'العنوان',
  'reg_website': 'الموقع الإلكتروني',
  'reg_manager_name': 'اسم المدير',
  'reg_submit': 'إنشاء حساب',

  // forgot password
  'fp_enter_id': 'يرجى إدخال رقم الهوية',
  'fp_error': 'حدث خطأ',
  'fp_title': 'نسيت كلمة المرور؟',
  'fp_subtitle': 'أدخل رقم الهوية وسنرسل لك رابط إعادة التعيين',
  'fp_id_field': 'رقم الهوية / السجل التجاري',
  'fp_next': 'التالي',
  'fp_choose_method': 'اختر طريقة استلام الرابط',
  'fp_method_subtitle': 'سيصلك رابط لإعادة تعيين كلمة المرور',
  'fp_email': 'إرسال على الإيميل',
  'fp_sms': 'إرسال على الجوال',
  'fp_sent': 'تم إرسال الرابط!',
  'fp_sent_body': 'افتح الرابط المرسل وستنتقل لصفحة تغيير كلمة المرور.\nالرابط صالح لمدة 10 دقائق.',

  // profile
  'prof_load_error': 'تعذر تحميل البيانات',
  'prof_retry': 'إعادة المحاولة',
  'prof_edit': 'تعديل المعلومات الشخصية',
  'prof_full_name': 'الاسم الكامل',
  'prof_email': 'البريد الإلكتروني',
  'prof_phone': 'رقم الجوال',
  'prof_job_title': 'المسمى الوظيفي',
  'prof_employer': 'جهة العمل',
  'prof_skills_count': 'عدد المهارات',
  'prof_certs_count': 'عدد الشهادات',
  'prof_career': 'السجل الوظيفي',
  'prof_education': 'التعليم',
  'prof_no_career': 'لا يوجد سجل وظيفي بعد',
  'prof_no_education': 'لا يوجد سجل تعليمي بعد',
  'prof_add_career': 'إضافة وظيفة',
  'prof_company': 'الشركة / الجهة',
  'prof_job': 'المسمى الوظيفي',
  'prof_start_date': 'تاريخ البداية (YYYY-MM-DD)',
  'prof_end_date': 'تاريخ الانتهاء (اتركه فارغاً إن لا يزال)',
  'prof_description': 'وصف (اختياري)',
  'save': 'حفظ',
  'prof_add_edu': 'إضافة مؤهل تعليمي',
  'prof_university': 'الجامعة / المدرسة',
  'prof_degree': 'الدرجة العلمية (بكالوريوس، ماجستير...)',
  'prof_major': 'التخصص (اختياري)',
  'prof_edu_start': 'سنة البداية (YYYY-MM-DD)',
  'prof_edu_end': 'سنة الانتهاء (اتركه فارغاً إن لا يزال)',
  'since': 'منذ',
  'present': 'حتى الآن',
  'current': 'حالي',
  'add': 'إضافة',

  // certified documents
  'cert_request': 'طلب شهادة',
  'cert_title': 'شهاداتك الموثقة',
  'cert_subtitle': 'هنا تجد جميع الشهادات التي تم التحقق منها وتوثيقها',
  'cert_empty': 'لا توجد شهادات موثقة بعد',
  'cert_verified': 'موثقة',
  'cert_issue_date': 'تاريخ الإصدار',
  'cert_hash': 'هاش البلوكشين',
  'back': 'رجوع',
  'cert_major': 'التخصص / الوصف',

  // employment history
  'emp_title': 'تاريخ التوظيف',
  'emp_delete_error': 'تعذر حذف السجل',
  'emp_add': 'إضافة وظيفة',
  'emp_company': 'اسم الشركة',
  'emp_job': 'المسمى الوظيفي',
  'emp_start': 'تاريخ البدء (YYYY-MM-DD)',
  'emp_end': 'تاريخ الانتهاء (اتركه فارغاً إن كان حالياً)',
  'emp_desc': 'الوصف (اختياري)',
  'emp_fill': 'يرجى تعبئة الحقول المطلوبة',
  'error': 'خطأ',
  'emp_empty': 'لا يوجد سجل وظيفي بعد',

  // edit profile
  'edit_title': 'تعديل الملف الشخصي',
  'edit_photo': 'اضغط لتغيير الصورة',
  'edit_first': 'الاسم الأول',
  'edit_father': 'اسم الأب',
  'edit_last': 'اسم العائلة',
  'edit_email': 'البريد الإلكتروني',
  'edit_phone': 'رقم الجوال',
  'edit_saved': 'تم الحفظ بنجاح',
  'edit_save_error': 'خطأ في الحفظ',

  // request certificate
  'req_title': 'طلب توثيق شهادة',
  'req_subtitle': 'أدخل معلومات الشهادة بدقة ليتم مراجعتها وتوثيقها من قبل فريقنا.',
  'req_cert_name': 'اسم الشهادة / الدورة',
  'req_issuer': 'الجهة المصدرة للشهادة',
  'req_date': 'تاريخ الحصول (YYYY-MM-DD)',
  'req_file': 'صورة أو ملف الشهادة (اختياري)',
  'req_upload': 'اضغط لرفع صورة أو PDF',
  'req_remove': 'إزالة الملف',
  'req_send': 'إرسال الطلب',
  'req_fill': 'يرجى تعبئة جميع الحقول',
  'req_success': 'تم إرسال طلب التوثيق بنجاح',
  'req_error': 'خطأ في إرسال الطلب',

  // company profile
  'comp_load_error': 'تعذر تحميل بيانات المنشأة',
  'comp_email': 'البريد الرسمي:',
  'comp_phone': 'رقم الجوال:',
  'comp_uid': 'الرقم التعريفي:',
  'comp_edit': 'تعديل بيانات المنشأة',

  // search by id
  'search_title': 'بحث بالرقم التعريفي',
  'search_uid_label': 'الرقم التعريفي للموظف:',
  'search_btn': 'بحث',
  'search_national_id': 'الهوية الوطنية:',
  'search_phone': 'رقم الجوال:',
  'search_email': 'البريد الإلكتروني:',
  'search_skills': 'المهارات المكتسبة:',
  'search_certified': 'موثقة',
  'search_certs': 'الشهادات الموثقة:',
  'search_career_hist': 'تاريخ التوظيف:',

  // search by description
  'desc_title': 'وصف الموظف المطلوب',
  'desc_placeholder': 'مبرمج تطبيقات',
  'desc_label': 'اكتب الوصف:',
  'desc_btn': 'ابحث',
  'desc_no_results': 'لم يتم العثور على نتائج',
  'desc_results': 'نتائج البحث:',
  'desc_employee': 'موظف',
  'desc_unemployed': 'عاطل',
  'desc_reason': 'سبب التطابق:',
  'desc_error': 'خطأ في البحث',

  // change job
  'job_title': 'تغيير المسمى الوظيفي',
  'job_uid': 'الرقم التعريفي للموظف:',
  'job_current': 'الوظيفة الحالية:',
  'job_join_date': 'تاريخ الانضمام:',
  'job_new_title': 'المسمى الوظيفي الجديد:',
  'job_confirm': 'تأكيد التحديث',
  'job_success': 'تم تحديث المسمى الوظيفي بنجاح',
  'job_history': 'السجل المهني السابق:',

  // courses
  'course_title': 'الدورات',
  'course_empty': 'لا توجد دورات حالياً',
  'course_add': 'إضافة دورة تدريبية',
  'course_trainee': 'متدرب',
  'course_details': 'عرض التفاصيل',

  // trainer profile
  'train_load_error': 'تعذر تحميل بيانات المؤسسة',
  'train_updated': 'تم تحديث البيانات بنجاح',
  'train_update_error': 'خطأ في التحديث',
  'train_email': 'البريد:',
  'train_phone': 'الجوال:',
  'train_name': 'اسم المؤسسة',
  'train_email_field': 'البريد الإلكتروني',
  'train_phone_field': 'رقم الجوال',
  'train_edit': 'تعديل بيانات المؤسسة',
  'train_save': 'حفظ التغييرات',

  // skills page
  'skill_add_title': 'إضافة مهارة مكتسبة:',
  'skill_name_label': 'اسم المهارة:',
  'skill_placeholder': 'مثل: Python، إدارة المشاريع، التسويق...',
  'skill_cert_label': 'إرفاق شهادة داعمة (اختياري):',
  'skill_camera': 'الكاميرا',
  'skill_device': 'من الجهاز',
  'skill_name_required': 'يرجى كتابة اسم المهارة',
  'skill_gen_error': 'خطأ في توليد الاختبار',
  'skill_submit': 'إرسال الإجابات',
  'skill_eval_error': 'خطأ في التقييم',
  'skill_write_hint': 'اكتب إجابتك هنا...',
  'skill_levels': 'سيتم تصنيف مستوى المهارة حسب الميدالية:',
  'skill_expert': 'خبير\n(ذهبي ≥85%)',
  'skill_advanced': 'متقدم\n(فضي 60-84%)',
  'skill_beginner': 'مبتدئ\n(برونزي <60%)',
  'skill_quiz_label': 'اختبار:',
  'skill_ai_eval': 'تقييم الذكاء الاصطناعي',
  'skill_medal': 'ميدالية',
  'skill_gold': 'ذهبي',
  'skill_silver': 'فضي',
  'skill_bronze': 'برونزي',
  'skill_score': 'نتيجتك:',
  'skill_certified_badge': 'مهارة موثقة بشهادة',
  'skill_add_another': 'إضافة مهارة أخرى',
  'skill_capture': 'التقاط صورة الشهادة',
  'skill_camera_denied': 'لم يتم السماح بالوصول إلى الكاميرا.\nتأكد من منح الإذن في المتصفح.',
  'skill_capture_btn': 'التقاط',

  // skills dashboard
  'dash_title': 'لوحة المهارات المكتسبة:',
  'dash_empty': 'لم تضف أي مهارات بعد.\nاذهب لتبويب المهارات لإضافة مهارتك.',
  'dash_view_cert': 'عرض الشهادة الداعمة',
  'dash_ai_eval': 'تقييم الذكاء الاصطناعي',
  'dash_no_feedback': 'لا يوجد تقييم مفصّل لهذه المهارة.',
  'dash_certified': 'موثق',
  'medal_gold': 'ذهبي',
  'medal_silver': 'فضي',
  'medal_bronze': 'برونزي',
  'level_expert': 'خبير',
  'level_advanced': 'متقدم',
  'level_intermediate': 'متوسط',
  'level_beginner': 'مبتدئ',
};
